# Generated by Django 2.2 on 2020-08-19 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tipoMaterial', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('anio', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Biblioteca_3.Material')),
                ('editorial', models.CharField(max_length=50)),
            ],
            bases=('Biblioteca_3.material',),
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Biblioteca_3.Material')),
                ('paginas', models.IntegerField()),
            ],
            bases=('Biblioteca_3.material',),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSalida', models.DateField()),
                ('fechaRegreso', models.DateField()),
                ('prestamoLibro', models.ManyToManyField(to='Biblioteca_3.Libro')),
                ('prestamoRevista', models.ManyToManyField(to='Biblioteca_3.Revista')),
            ],
        ),
    ]
