# Generated by Django 2.2 on 2020-08-19 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPersona', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('numLibros', models.IntegerField()),
                ('adeudo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Biblioteca_3.Persona')),
                ('matricula', models.IntegerField()),
            ],
            bases=('Biblioteca_3.persona',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Biblioteca_3.Persona')),
                ('numEmpleado', models.IntegerField()),
            ],
            bases=('Biblioteca_3.persona',),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='prestamoAlumno',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_3.Alumno'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='prestamoProfesor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_3.Profesor'),
        ),
    ]
