# Generated by Django 2.2 on 2020-08-19 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_3', '0002_auto_20200819_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='prestamoAlumno',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_3.Alumno'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='prestamoLibro',
            field=models.ManyToManyField(blank=True, to='Biblioteca_3.Libro'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='prestamoProfesor',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_3.Profesor'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='prestamoRevista',
            field=models.ManyToManyField(blank=True, to='Biblioteca_3.Revista'),
        ),
    ]
