# Generated by Django 2.2 on 2020-08-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_3', '0004_auto_20200819_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, default='fotos_tapa/default.png', upload_to='fotos_tapa/'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='adeudo',
            field=models.IntegerField(null=True),
        ),
    ]
